spring.application.name=link-shortener-service
server.port=8088

spring.datasource.url=jdbc:postgresql://localhost:5433/url_shortener_db
spring.datasource.username=local
spring.datasource.password=local

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.database-change-log-lock-table=LIQ_DATABASECHANGELOGLOCK
spring.liquibase.database-change-log-table=LIQ_DATABASECHANGELOG
spring.liquibase.driver-class-name=org.postgresql.Driver
spring.liquibase.liquibase-schema=public
spring.liquibase.user=${spring.datasource.username}
spring.liquibase.password=${spring.datasource.password}
spring.liquibase.url=${spring.datasource.url}